easy_admin:
    site_name: 'Mediterra'

    entities:
        # List the entity class name you want to manage
        Events:
            class: App\Entity\Events
            new:
                fields:
                    - 'title'
                    - 'omschrijving'
                    - 'date'
                    - {property: 'image', type: 'file'}
        Posts:
            class: App\Entity\Posts
            new:
                fields:
                    - 'title'
                    - 'omschrijving'
                    - {property: 'image', type: 'file'}



